
[[artifacts]]
git-tree-sha1 = "6a96be57af7646264dbf2410329fa3bb97524f02"
os = "linux"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Magic.jl/releases/download/v0.6.2/artifacts-linux-x86_64.tar.gz"
    sha256 = "5dc68efd75bbe197c54d3b0b9bdb569edfc8907e28f2ce4d070016e5e0616e55"

[[artifacts]]
git-tree-sha1 = "dc2175fbbb8eb4ad681477dfe51a2e4ca034d7c2"
os = "windows"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Magic.jl/releases/download/v0.6.2/artifacts-win64.tar.gz"
    sha256 = "98de3182920ea5b53b2721d3a327e866eaa14fd46e9f8c2dd5ca20da2b8eaa2c"

