
function buffer_to_string(buffer::NTuple{N, UInt8}) where N
    # Find the null terminator
    null_pos = findfirst(==(0x00), buffer)
    if null_pos === nothing
        # No null terminator, use entire buffer
        return String(collect(buffer))
    else
        # Convert only up to null terminator
        return String(collect(buffer[1:null_pos-1]))
    end
end

function string_to_buffer(::Val{N}, s::AbstractString)::NTuple{N, UInt8} where N
    bytes = codeunits(s)
    maxlen = N - 1
    len = min(length(bytes), maxlen)

    return ntuple(i ->
        i <= len ? bytes[i] :
        i == len + 1 ? 0x00 :
        0x00,
        N
    )
end

function remove_lines_starting_with(err::String, prefix::String)::String
    lines = split(err, '\n')
    keep = filter(l -> !startswith(lstrip(l), prefix), lines)
    return join(keep, '\n')
end

function try_rm(path::String; kwargs...)::Bool
    try
        rm(path; kwargs...)
        return true
        catch e
        return false
    end
end

# NOTE: functions to open browser. Copied from LiveServer.jl
#-------------------------------------------------------------
function detectwsl()
    Sys.islinux() &&
    isfile("/proc/sys/kernel/osrelease") &&
    occursin(r"Microsoft|WSL"i, read("/proc/sys/kernel/osrelease", String))
end

function open_in_default_browser(url::AbstractString)::Bool
    try
        if Sys.isapple()
            Base.run(`open $url`)
            true
        elseif Sys.iswindows() || detectwsl()
            Base.run(`cmd.exe /s /c start "" /b $url`)
            true
        elseif Sys.islinux()
            Base.run(`xdg-open $url`)
            true
        else
            false
        end
    catch
        false
    end
end

function is_valid_hostname(hostname::String)
    # Overall length limit
    length(hostname) > 253 && return false
    isempty(hostname) && return false

    # Split into labels and validate each
    labels = split(hostname, '.')
    for label in labels
        isempty(label) && return false
        length(label) > 63 && return false
        # Must start/end with alphanumeric, may contain hyphens in the middle
        occursin(r"^[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?$", label) || return false
    end

    return true
end

function assert_string_in_list(arg::Tuple, white_list::Tuple)::Nothing
    arg[2] in white_list || throw(InvalidArgument(arg, "`$(arg[1])` should be one of these: $(white_list)."))
    return nothing
end

function assert_key_in_dict(arg::Tuple, dict::Dict)::Nothing
    haskey(dict, arg[2]) || throw(InvalidArgument(arg, "`$(arg[1])` : $(white_list)."))
    return nothing
end

function assert_valid_material_icon(args::Tuple)::Nothing
    if !startswith(args[2], "material/")
        throw(InvalidArgument(args, "`icon` must have the format \"material/icon_name\". Example: \"material/person\""))
    end

    icon_name = replace(args[2], "material/" => "")
    if !haskey(MATERIAL_ICON_CODEPOINTS, icon_name)
        throw(InvalidArgument(args, "\"$(icon_name)\" is not a valid icon name. Checkout https://fonts.google.com/icons?icon.set=Material+Icons to find the name of the icon you want."))
    end
    return nothing
end

function function_accepts_arg_count(f::Function, arg_count::Int)::Bool
    ms = methods(f)
    ok = any(ms) do m
        m.nargs-1 == arg_count
    end
    return ok
end

function get_item_by_its_stringified_version(list::Union{Vector, Tuple}, rep::String)::Any
    for entry in list
        if typeof(entry) <: Number
            rep_number = tryparse(typeof(entry), rep)
            if !isnothing(rep_number)
                if isapprox(entry, rep_number, atol=0.000000001)
                    return entry
                end
            end
        elseif entry == rep
            return entry
        end
    end
    return missing
end

function print_stacktrace(;skip::Int=0)::Nothing
    frames = stacktrace()
    println(sprint(Base.show_backtrace, frames[(skip+1):end]))
    return nothing
end

function caller_location()::String
    frame = stacktrace()[4]
    return "$(frame.file):$(frame.line)"
end

function ismithing(value::Any)::Bool
    return ismissing(value) || isnothing(value)
end

function coalesce(args...)
    for arg in args
        if !ismithing(arg)
            return arg
        end
    end
    return nothing
end

"""
# is_valid_mime_or_extension(s::AbstractString)::Bool

Returns `true` if `s` is a syntactically valid MIME type (e.g. "image/png",
"image/*", "*/*") or a valid file extension (e.g. ".png", ".tar.gz").
"""
function is_valid_mime_or_extension(s::AbstractString)::Bool
    # NOTE: Generated by Claude.

    s = strip(s)
    isempty(s) && return false

    # MIME token per RFC 6838 (letters, digits, !#&-^_.+), or a bare wildcard "*"
    token = "(?:[a-zA-Z0-9][a-zA-Z0-9!#&\\-\\^_.+]*|\\*)"
    mime_re = Regex("^" * token * "/" * token * "\$")

    # File extension: leading dot, then dot-separated alphanumeric segments
    ext_re = r"^\.[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*\$"

    return occursin(mime_re, s) || occursin(ext_re, s)
end

function is_valid_filename(name::AbstractString)::Bool
    # NOTE: Generated by Claude.
    isempty(name) && return false

    # Reject reserved/problematic characters (covers Windows + general safety)
    # Windows forbids: < > : " / \ | ? *  and control chars
    if occursin(r"[<>:\"/\\|?*\x00-\x1F]", name)
        return false
    end

    # Reject names that are just dots (., ..)
    name in (".", "..") && return false

    # Reject trailing dot or space (Windows-specific issue)
    if endswith(name, ".") || endswith(name, " ")
        return false
    end

    # Reject Windows reserved names (case-insensitive), with or without extension
    reserved = ["CON", "PRN", "AUX", "NUL",
                ("COM$i" for i in 1:9)...,
                ("LPT$i" for i in 1:9)...]
    base = split(name, '.')[1]
    if uppercase(base) in reserved
        return false
    end

    # Optional: length limit (255 is common on many filesystems)
    if length(name) > 255
        return false
    end

    return true
end

function normalize_html_color(s::AbstractString)::Union{String,Nothing}
    s = lowercase(strip(s))

    # Full 6-digit hex, with or without leading #
    m = match(r"^#?([0-9a-f]{6})$", s)
    if m !== nothing
        return "#" * m.captures[1]
    end

    # Short 3-digit hex, expand each digit
    m = match(r"^#?([0-9a-f])([0-9a-f])([0-9a-f])$", s)
    if m !== nothing
        r, g, b = m.captures
        return "#" * r*r * g*g * b*b
    end

    return nothing  # invalid / unsupported (e.g. named colors, rgb(), etc.)
end

function stringify(number::Real; precision::Union{Int,Nothing}=nothing, decimal_separator::String=".", thousands_separator::String=",")::String
    value = isnothing(precision) ? string(number) : @sprintf("%.*f", precision, number)

    neg = startswith(value, "-")
    value = lstrip(value, '-')

    parts = split(value, ".")
    intpart = parts[1]

    left = ""
    for (i, c) in enumerate(Iterators.reverse(intpart))
        if i > 1 && (i - 1) % 3 == 0
            left = thousands_separator * left
        end
        left = c * left
    end

    result = neg ? "-" * left : left
    if length(parts) > 1
        result *= decimal_separator * parts[2]
    end
    return result
end


